#!/usr/bin/env python3
import rospy
from task_board_localization.srv import PointDetect, PointDetectRequest, PointDetectResponse

from geometry_msgs.msg import Pose, PoseStamped
from sensor_msgs.msg import PointCloud2

def point_detect_client(record):
    '''
    running of the perception service client
    @return:
    '''
    print("check")
    rate = rospy.Rate(1)

    try:
        # Obtain a single pointcloud2
        point_cloud = rospy.wait_for_message("/camera/depth/color/points", PointCloud2)
        point_detect = rospy.ServiceProxy("/point_detect", PointDetect)
        rospy.loginfo("WAITING FOR SERVICE")

        # Send point cloud the server
        rospy.wait_for_service("/point_detect",5)
        resp = point_detect(point_cloud, record)
        rospy.loginfo("retrieved iterative closest point")
        rate.sleep()

        return resp
    except rospy.ServiceException as e:
        print("Service call failed")
        print(e)
    return


if __name__ == "__main__":
    rospy.init_node("point_client")
    record = False
    resp: PointDetectResponse = point_detect_client(record)
    trans_rot_pub = rospy.Publisher("/trans_rot", PoseStamped, queue_size=0)
    print(resp.pose)
    while not rospy.is_shutdown():
        trans_rot_pub.publish(resp.pose)
    rospy.spin()



