#!/usr/bin/env python3

import rospy

from dynamic_reconfigure.server import Server
from object_localization.cfg import FilterValuesConfig

def callback(config, level):
    return config
 
if __name__ == "__main__":
    rospy.init_node("filter_server", anonymous = False)
 
    srv = Server(FilterValuesConfig, callback)
    rospy.spin()
