board_touch:
  board_dimensions:
    width: 0.15
    length: 0.26
    height: 0.09
  clearance: 0.1
  force_threshold: 10

stiffness:
  K_pos: 4000
  K_z: 4000
  K_ori: 40

pose_box_ref_guess:
  trans_ref_guess: [0.60, 0.18, 0.09]
  rot_ref_guess: [0.5736, 0, 0, -0.8192]

transform_cam:
  trans_cam: [0.62, 0.01, 0.383]
  rot_cam: [0.001, 0.736, -0.677, -0.013]

cartesian_pose_topic_name: '/cartesian_pose'
force_torque_ext_topic: '/force_torque_ext'
equilibrium_pose_topic: '/equilibrium_pose'
pose_ref_2_new_topic: '/pose_ref_2_new'
